feat: add border radius tab
gravity-ui/landing pull request #220
Opened 2024-06-26 13:47 UTC by Arucard89

2024-06-27 14:10 UTC, amje requested changes

2024-06-27 14:10 UTC, amje commented on src/components/Themes/lib/themeCreatorUtils.ts
> +}
Так не надо делать, это приватные переменные. Если там border не управляется переменными темы, значит надо это починить

2024-06-28 11:22 UTC, Arucard89 commented on src/components/Themes/lib/themeCreatorUtils.ts
> +}
сделал ПР в uikit на замену строкового значения константой: https://github.com/gravity-ui/uikit/pull/1682

2024-06-28 15:21 UTC, Arucard89 commented on src/components/Themes/lib/themeCreatorUtils.ts
> +}
убрал карточки из превью и убрал XXL размер, потому что он нигде не используется: 
https://github.com/gravity-ui/landing/pull/220/commits/3aff60787771a6406377e69533afa37352d48bc4

2024-07-02 11:02 UTC, Arucard89 commented on src/components/Themes/lib/themeCreatorUtils.ts
> +}
@amje , посмотри, пожалуйста, фикс

2024-07-04 06:35 UTC, merged