feat: add Overlay docs
gravity-ui/landing pull request #228
Opened 2024-07-02 09:15 UTC by Vladeeg

2024-07-02 19:00 UTC, amje requested changes

2024-07-03 09:39 UTC, Vladeeg commented on src/content/components/uikit/Overlay/index.ts
> +                type: 'select',
done

2024-07-06 16:56 UTC, amje approved these changes

2024-07-07 11:35 UTC, imsitnikov approved these changes

2024-07-08 10:02 UTC, merged