Marked figma file as completed task in the roadmap section
gravity-ui/landing pull request #84
Opened 2023-08-28 16:04 UTC by vvtimofeev

2023-08-28 16:39 UTC, amje requested changes

2023-08-29 06:11 UTC, vvtimofeev commented on src/content/roadmap.ts
> +        status: RoadmapTaskStatus.Completed,
Moved up date time library in roadmap.

2023-08-29 07:19 UTC, imsitnikov approved these changes

2023-08-29 11:50 UTC, amje approved these changes

2023-08-29 11:50 UTC, merged