Added news about figma public file to the main page
gravity-ui/landing pull request #85
Opened 2023-08-28 16:05 UTC by vvtimofeev

2023-08-28 17:38 UTC, imsitnikov requested changes

2023-08-28 17:38 UTC, imsitnikov commented on src/content/landing.ts
> +                            'Our Figma library is finally released and available <a href="https://www.figma.com/community/file/1271150067798118027/Gravity-UI-Design-System-(Beta)">here</a>. Currently
Incorrect quotas, plz change to:
```
'Our Figma library is finally released and available <a href="https://www.figma.com/community/file/1271150067798118027/Gravity-UI-Design-System-(Beta)">here</a>. Currently it\'s in Beta so we\'d love for you to test it out and share your feedback with us.'
```

2023-08-29 06:13 UTC, vvtimofeev commented on src/content/landing.ts
> +                            'Our Figma library is finally released and available <a href="https://www.figma.com/community/file/1271150067798118027/Gravity-UI-Design-System-(Beta)">here</a>. Currently
My fault, sorry. Changed it.

2023-08-29 07:20 UTC, imsitnikov approved these changes

2023-08-29 07:23 UTC, merged